services:
  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:${BACKEND_PORT}

  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    # depends_on:
    #   - db
    environment:
      - DB_USER=${POSTGRES_USER}
      - DB_HOST=anime-watchlist-db.cdmso2a6i94o.us-east-1.rds.amazonaws.com
      - DB_NAME=${POSTGRES_DB}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_PORT=${DB_PORT}

  ml:
    build: ./ml
    ports:
      - "${ML_PORT}:${ML_PORT}"

#   db:
#     image: postgres:13
#     environment:
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#       POSTGRES_DB: ${POSTGRES_DB}
#     ports:
#       - "${DB_PORT}:${DB_PORT}"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: