version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:${BACKEND_PORT}
    volumes:
      - ./frontend:/app  # Mount your local frontend directory
      - /app/node_modules  # Avoid overriding the node_modules inside the container
    command: ["npm", "run", "dev"]  # Use Next.js dev mode for live reloading

  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - db
    environment:
      - DB_USER=${POSTGRES_USER}
      - DB_HOST=db
      - DB_NAME=${POSTGRES_DB}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_PORT=${DB_PORT}
    volumes:
      - ./backend:/app  # Mount your local backend directory
      - /app/node_modules  # Prevent overriding node_modules
    command: ["npm", "run", "dev"]  # Use nodemon for live reload in development

  ml:
    build: ./ml
    ports:
      - "${ML_PORT}:${ML_PORT}"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
